
#
# BasicMsg by zProgramm
# Version: 1.0
#


config:

  prefix: "&a[Bmsg] &8|"
  p-variable: "%c"

  error: "&c[Error] &8|"
  e-variable: "%e"

  perms:
    reload: bmsg.reload
    socialspy: bmsg.socialspy
    color: bmsg.color

  metrics: true
  update-check: false