
#
# BasicMsg by zProgramm
# Version: 1.2
#


config:

  prefix: "&a[Bmsg] &8|"
  p-variable: "%c"

  error: "&c[Error] &8|"
  e-variable: "%e"

  perms:
    chat-color: bmsg.chat.color
    reload: bmsg.reload
    socialspy: bmsg.socialspy
    toggle-admin: bmsg.mtoggle.admin

  metrics: true
  update-check: false
  # If you allow the subcommand to go to the support of the plugin /bmsg support.
  allow-support: false